/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ie.philb.testorderingsoapclient.ui.nav;

/**
 *
 * @author philb
 */
public class LeftNavPanel extends javax.swing.JPanel {

    /**
     * Creates new form LeftNavPanel
     */
    public LeftNavPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane2 = new javax.swing.JTabbedPane();
        ordersNavPanel1 = new ie.philb.testorderingsoapclient.ui.nav.orders.OrdersNavPanel();
        productsPanel1 = new ie.philb.testorderingsoapclient.ui.nav.products.ProductsPanel();

        jTabbedPane2.setTabPlacement(javax.swing.JTabbedPane.BOTTOM);
        jTabbedPane2.addTab("Orders", ordersNavPanel1);
        jTabbedPane2.addTab("Products", productsPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane2, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 263, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane jTabbedPane2;
    private ie.philb.testorderingsoapclient.ui.nav.orders.OrdersNavPanel ordersNavPanel1;
    private ie.philb.testorderingsoapclient.ui.nav.products.ProductsPanel productsPanel1;
    // End of variables declaration//GEN-END:variables
}
