/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ie.philb.testorderingsoapclient.ui.nav.products;

import ie.philb.testorderingsoapclient.Application;
import ie.philb.testorderingsoapclient.ApplicationListener;
import ie.philb.testorderingsoapclient.ui.nav.orders.OrderCategory;
import ie.philb.testorderingsoapclient.ws.Order;
import ie.philb.testorderingsoapclient.ws.Product;
import java.awt.datatransfer.StringSelection;
import java.awt.datatransfer.Transferable;
import java.util.List;
import javax.swing.JComponent;
import javax.swing.TransferHandler;
import static javax.swing.TransferHandler.COPY;

/**
 *
 * @author philb
 */
public class ProductsPanel extends javax.swing.JPanel implements ApplicationListener {

    /**
     * Creates new form ProductsPanel
     */
    public ProductsPanel() {
        initComponents();
        jList1.setModel(new ProductListModel());
        jList1.setCellRenderer(new ProductListCellRenderer());
        jList1.setDragEnabled(true);

        jList1.setTransferHandler(new TransferHandler() {

            @Override
            public int getSourceActions(JComponent comp) {
                return COPY;
            }

            @Override
            public Transferable createTransferable(JComponent comp) {
                int idx = jList1.getSelectedIndex();

                if (idx == -1) {
                    return null;
                }

                ProductListModel model = (ProductListModel) jList1.getModel();
                Product p = model.getElementAt(idx);

                if (p == null) {
                    return null;
                }

                String dragText = p.getSkuCode();
                return new StringSelection(dragText);
            }
        });

        Application.getApplication().addListener(this);
    }

    public void setProducts(List<Product> products) {
        ProductListModel m = (ProductListModel) jList1.getModel();
        m.setProducts(products);
    }

    @Override
    public void orderUpdated(Order oldOrder, Order order) {
        Application app = Application.getApplication();
        List<Product> products = app.getProducts();
        setProducts(products);
    }

    @Override
    public void productsUpdated() {
    }
    
        
    @Override
    public void categoryUpdated(OrderCategory category) {
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();

        jList1.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 116, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 197, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList jList1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

}
