/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ie.philb.testorderingsoapclient.ui;

import ie.philb.testorderingsoapclient.Application;
import ie.philb.testorderingsoapclient.ApplicationListener;
import ie.philb.testorderingsoapclient.commands.NewOrderCommand;
import ie.philb.testorderingsoapclient.ui.nav.orders.OrderCategory;
import ie.philb.testorderingsoapclient.ws.Order;
import ie.philb.testorderingsoapclient.ws.Party;
import ie.philb.testorderingsoapclient.ws.ServiceException_Exception;
import java.awt.Dimension;
import javax.swing.JOptionPane;

/**
 *
 * @author philb
 */
public class MainFrame extends javax.swing.JFrame implements ApplicationListener {

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
        setPreferredSize(new Dimension(1000, 600));
        setSize(getPreferredSize());
        jSplitPane1.setDividerLocation(185);

        Application.getApplication().addListener(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        statusBar1 = new ie.philb.testorderingsoapclient.ui.StatusBar();
        jSplitPane1 = new javax.swing.JSplitPane();
        jSplitPane2 = new javax.swing.JSplitPane();
        orderForm2 = new ie.philb.testorderingsoapclient.ui.orderform.OrderForm();
        ordersListPanel1 = new ie.philb.testorderingsoapclient.ui.nav.orders.OrdersListPanel();
        jSplitPane3 = new javax.swing.JSplitPane();
        ordersFolderPanel1 = new ie.philb.testorderingsoapclient.ui.nav.orders.OrdersFolderPanel();
        jPanel1 = new javax.swing.JPanel();
        jToolBar1 = new javax.swing.JToolBar();
        btnConnect = new javax.swing.JButton();
        btnNew = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jSplitPane1.setDividerLocation(182);

        jSplitPane2.setDividerLocation(180);
        jSplitPane2.setRightComponent(orderForm2);
        jSplitPane2.setLeftComponent(ordersListPanel1);

        jSplitPane1.setRightComponent(jSplitPane2);

        jSplitPane3.setDividerLocation(100);
        jSplitPane3.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);
        jSplitPane3.setTopComponent(ordersFolderPanel1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 179, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 204, Short.MAX_VALUE)
        );

        jSplitPane3.setRightComponent(jPanel1);

        jSplitPane1.setLeftComponent(jSplitPane3);

        jToolBar1.setRollover(true);

        btnConnect.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ie/philb/testorderingsoapclient/icons/connect.png"))); // NOI18N
        btnConnect.setFocusable(false);
        btnConnect.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnConnect.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnConnect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConnectActionPerformed(evt);
            }
        });
        jToolBar1.add(btnConnect);

        btnNew.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ie/philb/testorderingsoapclient/icons/new.png"))); // NOI18N
        btnNew.setEnabled(false);
        btnNew.setFocusable(false);
        btnNew.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnNew.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewActionPerformed(evt);
            }
        });
        jToolBar1.add(btnNew);

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(statusBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jSplitPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 576, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(jSplitPane1)
                .addGap(1, 1, 1)
                .addComponent(statusBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnConnectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConnectActionPerformed
        try {
            Application.getApplication().load();
        } catch (ServiceException_Exception sx) {
            JOptionPane.showMessageDialog(this, sx.getMessage());
        }
    }//GEN-LAST:event_btnConnectActionPerformed

    private void btnNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewActionPerformed
        Party buyer = Application.getApplication().getBuyer();

        if (buyer == null) {
            return;
        }

        try {
            Order order = new NewOrderCommand().execute(buyer);
            Application.getApplication().setOrder(order);
        } catch (Exception ex) {
            handleException(ex);
        }
    }//GEN-LAST:event_btnNewActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConnect;
    private javax.swing.JButton btnNew;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JSplitPane jSplitPane2;
    private javax.swing.JSplitPane jSplitPane3;
    private javax.swing.JToolBar jToolBar1;
    private ie.philb.testorderingsoapclient.ui.orderform.OrderForm orderForm2;
    private ie.philb.testorderingsoapclient.ui.nav.orders.OrdersFolderPanel ordersFolderPanel1;
    private ie.philb.testorderingsoapclient.ui.nav.orders.OrdersListPanel ordersListPanel1;
    private ie.philb.testorderingsoapclient.ui.StatusBar statusBar1;
    // End of variables declaration//GEN-END:variables

    private void handleException(Exception ex) {
        JOptionPane.showMessageDialog(this, ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
    }

    @Override
    public void productsUpdated() {
        Application app = Application.getApplication();
        btnNew.setEnabled(!app.getProducts().isEmpty());
    }

    @Override
    public void orderUpdated(Order oldOrder, Order order) {
    }
    
        
    @Override
    public void categoryUpdated(OrderCategory category) {
        
    }
}
